### ISSUE TITLE
Bug: Search space glitches and small feedbacks

### ISSUE THREAD

**Issue by tamalCodes** [Tagggar/Firefox-Alpha#1]
**Please turn on the volume for a better experience.** 
Take a look at the quick video, maybe that'll clear out what i want to say.

https://github.com/Tagggar/Firefox-Alpha/assets/72851613/c20df834-07f8-43a9-8dd6-e06dfc4f131d

Also a quick thing is there a chance to hide these things ? It's really very distracting at this point.
![image](https://github.com/Tagggar/Firefox-Alpha/assets/72851613/35aed345-39ef-4671-ad69-6a437663d2ec)

**Comment by Tagggar** [comment]
Nice, glad you liked it, and thanks for the quality feedback.

### Search suggestions in URL bar are disabled intentionally for several reasons:

In some of my UX research, I found interesting results indicating that **disabling search suggestions** in the URL bar can **reduce cognitive load and help maintain focus.**

### 1. **`Productivity boost by lowering distractions and cognitive load`**
   Disabling search suggestions cultivates a sense of control, reducing distractions and improving satisfaction. Users can concentrate on their tasks, boosting efficiency and search accuracy. This minimalist approach is especially helpful for users who find constant suggestions overwhelming, thereby enhancing the overall UX.

>**Search suggestions are still available on search engine webpage.**
>Sometimes, search engine provides **[grammatically wrong suggestions](https://support.google.com/websearch/thread/56300495/sometimes-google-search-gives-me-grammatically-wrong-suggestions?hl=en)** (check google community forums for more info)

### 2. **`Data privacy`** 
Suggestions are often based on the user's browsing history, frequently visited websites, and search patterns. Consequently, this personal data can be vulnerable, leading to privacy violations or badly targeted advertising. Users may also feel uncomfortable with the notion that their search behavior is being tracked and used for commercial or other purposes without their explicit consent.

### 3. **`Echo chambers`**
The reliance on personalized suggestions may result in the formation of echo chambers, limiting users' exposure to diverse perspectives and information. This can potentially reinforce existing biases and restrict the exploration of alternative viewpoints.

> In other words, the user will begin to correctly formulate the search query, instead of choosing from suggestions.

**Comment by Tagggar** [comment]
### To disable search suggestions pop-up:

Type `about:config` in URL Bar and set: `browser.urlbar.maxRichResults` > `0`

or

Open `...` `/` `Firefox` `/` `Profiles` `/` `###.default-###` `/` `chrome` `/` `userChrome.css` file and add this code:

```
#urlbar-results { 
display: none !important;
}
```

Save file and restart Firefox. 

Suggestions pop-up won't bother you anymore 👍

**Comment by Tagggar** [comment]
Also, I see that your downloads button is not displayed.

### Downloads Button
"Check if your ⬇️ Downloads Button is hidden:

- `RMB` (Right-click) on the empty space in the Navigation Toolbar (top right corner) to open the menu;
- Click on `Customize Toolbar`;
- Drag the ⬇️ `Downloads Button` to the right corner of the Navigation Toolbar, and check [x] to enable auto-hide. 

Now, the downloads indicator will only be visible when there are any downloads.

**Comment by Tagggar** [comment]
### URL pop-up status panel
You can configure / hide it easily: 

1. Open `...` `/` `Firefox` `/` `Profiles` `/` `###.default-###` `/` `chrome` `/` `userChrome.css` file, and find by `Ctrl + F` the `statuspanel` code section. 

2. Edit the code to your preferences:

**Hide URL pop-up:**
```
/* 🔗 Status Panel [Url Popup] */
#statuspanel #statuspanel-label {
  display: none !important;
}
```

**Configure URL pop-up colors:**
```
/* 🔗 Status Panel [Url Popup] */
#statuspanel #statuspanel-label {
  font-weight: 600 !important;
  padding-inline: var(--6) !important;
  border-radius: var(--6) !important;
  margin: var(--8) !important;
  
  background-color: blue !important; /* 🟦blue backround color */
  color: white !important;           /* ⬜white text color     */
}
```

> For instance, replace `blue`  >  `grey` to make the pop-up less noticeable.

3. Save file and restart Firefox.

**Comment by Tagggar** [comment]
Absence of buttons is the unique feature - controls simplified by shortcuts.

> Window control buttons are rarely used (> 0.1% of the time) but take up space, disrupting interface consistency and simplicity.

You can close the browser by keyboard shortcuts or using the UI:

> `Alt + F4` - command will close the currently active window (Windows shortcut)

> `Ctrl + Shift + Q` - command will close the currently active window (Firefox shortcut)

> `Alt` > `File` > `Exit` - close the currently active window from browser menu

> Right-click on the Firefox icon on the Win taskbar > `Close window`

> Hover on the Firefox icon on the Win taskbar > click on `X`.

**Comment by tamalCodes** [comment]
Works like a charm thank you so much for the response. 

- I wanted to have something like this, is there a possibility that i can disable only the text appearing in the `top-left` corner while i  am placing a search ? The rest of the search suggestion works so nice.

- Can i have a place for some extensions. I mean by default the extensions are hidden, so if I want to use any `add on` or extension it is very difficult to do so.

![image](https://github.com/Tagggar/Firefox-Alpha/assets/72851613/1939ee2d-9204-4a4d-b654-95b082d83237)


### Update 1:

```css
#unified-extensions-button {
  z-index: 20;
  position: relative;
  margin-top: -20px;
  opacity: 0;
}
```

I added this little bit code, which has made the extensions button invisible, but if I click here i would be able to acess it. 
![image](https://github.com/Tagggar/Firefox-Alpha/assets/72851613/f366b992-9e86-4f8b-8c36-d9540c2a063f)

**Comment by Tagggar** [comment]
> I wanted to have something like this, is there a possibility that i can disable only the text appearing in the `top-left` corner while i  am placing a search ? The rest of the search suggestion works so nice.

It can be done, add this code to the end of `userChrome.css`:

```
/* Search Suggestions Fix*/
#urlbar-container #urlbar-input-container {
  opacity: 0;
}
.urlbarView {
  background-color: var(--lwt-accent-color); /* Pop-up background color (adaptive) */
  color: grey;                               /* Pop-up text color */
}
```

**Comment by Tagggar** [comment]
> Can i have a place for some extensions. I mean by default the extensions are hidden, so if I want to use any add on or extension it is very difficult to do so.

You can unhide Extensions button by deleting the `*/` :

```
/* ❌ Extensions Menu */
#unified-extensions-button,

to 

/* ❌ Extensions Menu
#unified-extensions-button,

```
Accordingly, you can edit a `❌ Hide Items ❌` section to unhide any element and adjust its position through the CSS or customization menu.

I aimed to create a code that is minimalistic yet highly configurable.

**Comment by tamalCodes** [comment]
Thanks, yes the code you wrote is one of the best documented code i have seen so far in such cases of themes. Thanks for such an amazing work. I have also modified the background and the bookmarks bar a little bit, to my liking.

Will be using this theme forever until a new release comes out 🚀
Thanks for replying back too, I'll close the issue now. You really helped me.

![image](https://github.com/Tagggar/Firefox-Alpha/assets/72851613/e9176b17-5cab-4f18-bff1-fb7e5ff7a681)

**Comment by kb12000** [comment]
> Thanks, yes the code you wrote is one of the best documented code i have seen so far in such cases of themes. Thanks for such an amazing work. I have also modified the background and the bookmarks bar a little bit, to my liking.
> 
> Will be using this theme forever until a new release comes out 🚀 Thanks for replying back too, I'll close the issue now. You really helped me.
> 
> ![image](https://user-images.githubusercontent.com/72851613/280919117-e9176b17-5cab-4f18-bff1-fb7e5ff7a681.png)

  @tamalCodes hey can i know the name of the homepage addon you are using???

**Comment by tamalCodes** [comment]
Hi @kb12000 , there's no addon i am using the background is added by updating the `userContent.css` and for the bookmark there has been some modifications made to the `userChrome.css`


#### Wallpaper:

```css
  body {
    background: url(camping.jpg) !important;
    background-size: cover !important;
    width: 100vw !important;
    height: 100vh !important;
  }
```

#### Bookmark

```css
#PersonalToolbar {
  padding: 0 !important;
  margin: 0 !important;
  max-height: none !important;
  background-color: var(--default) !important;
  border-radius: var(--6) !important;
  width: min-content !important;
}

#PlacesToolbarItems {
  display: flex;
  justify-content: center;
  margin: 5px 8px;
}

#PlacesToolbarItems>.bookmark-item {
  color: white !important;
  height: var(--tab-min-height);
}
```

Please add the default color to the root too. The color is `#2b2a33`, add it in this manner `--default: #2b2a33;`

**Comment by mghalix** [comment]
> > I wanted to have something like this, is there a possibility that i can disable only the text appearing in the `top-left` corner while i  am placing a search ? The rest of the search suggestion works so nice.
> 
> It can be done, add this code to the end of `userChrome.css`:
> 
> ```
> /* Search Suggestions Fix*/
> #urlbar-container #urlbar-input-container {
>   opacity: 0;
> }
> .urlbarView {
>   background-color: var(--lwt-accent-color); /* Pop-up background color (adaptive) */
>   color: grey;                               /* Pop-up text color */
> }
> ```

This worked well for a while, but now i noticed it stopped working only with the option where bookmarks toolbar is shown only in new tab, any workaround for this?

![image](https://github.com/user-attachments/assets/a1422913-0169-45e8-b1bc-61037a1566ae)
