### ISSUE TITLE
newtab bookmarks toolbar causes hidden items to bleed through

### ISSUE THREAD

**Issue by AeliusSaionji** [Tagggar/Firefox-Alpha#10]
This only happens when the bookmarks toolbar is set to only appear on new tabs.

![image](https://github.com/Tagggar/Firefox-Alpha/assets/4342746/93188a05-6577-4fda-8b98-9e8a37ea06b7)

**Comment by Tagggar** [comment]
See the https://github.com/Tagggar/Firefox-Alpha/issues/1#issuecomment-1793766243 in  Issue #1 for the solution.
