### ISSUE TITLE
Can't install theme

### ISSUE THREAD

**Issue by mateo-sheme** [Tagggar/Firefox-Alpha#17]
Found the theme really attractive. I followed the steps accordingly, but can't seem to figure why it isn't working. Here are some screenshots :
![Screenshot from 2024-01-11 21-06-30](https://github.com/Tagggar/Firefox-Alpha/assets/96703695/6a2f6167-06cb-456c-8a6e-6f16fe581124)
![Screenshot from 2024-01-11 21-06-53](https://github.com/Tagggar/Firefox-Alpha/assets/96703695/d829e263-11ec-4ff1-9ebf-21cb75ca8da2)
![Screenshot from 2024-01-11 21-06-12](https://github.com/Tagggar/Firefox-Alpha/assets/96703695/f7b30597-9573-419d-abd1-1796a255e53a)
![Screenshot from 2024-01-11 21-05-52](https://github.com/Tagggar/Firefox-Alpha/assets/96703695/393e8bd4-1efb-4d5e-a416-aed5613fbde3)

Thank you in advance!

**Comment by starlord101** [comment]
Put chrome folder in a default-release folder,  that's it

**Comment by mateo-sheme** [comment]
Works, sorry I am kinda new to this. Before I replaced the files to the permanent chrome folder
