### ISSUE TITLE
dude, i miss this theme so badly 

### ISSUE THREAD

**Issue by emslima** [Tagggar/Firefox-Alpha#25]
Since the update a few months ago the theme is broken and no one fix that, i try a lot fix even with AI and found out a issue with 
**-moz-user-focus: ignore;** are not work anymore, if anyone want to try fix that, and call me, i'll lovely help

**Comment by fvnky07** [comment]
i just found this theme and i miss it dammit :(

**Comment by emslima** [comment]
That make me change to Arc, and i'am happy again =)

**Comment by fvnky07** [comment]
yeah but arc not on Linux.

i suppose someone could fork this theme and fix it?

**Comment by emslima** [comment]
I try a lot even using AI, but no success
