### ISSUE TITLE
The menubar is empty

### ISSUE THREAD

**Issue by Naezr** [Tagggar/Firefox-Alpha#5]
The menubar is empty until I force it on and restart the browser
![изображение](https://github.com/Tagggar/Firefox-Alpha/assets/95460152/bb22a6e4-35e1-4e54-b7a0-79e9e0ad766d)

**Comment by Tagggar** [comment]
Seems like random Firefox bug - check Mozilla community forums for details: [Menu bar is gone and ALT does NOTHING](https://support.mozilla.org/en-US/questions/1235500#answer-1159593)


Try to delete `compatibility.ini` in the profile folder to make Firefox reinitialize the profile.

You can also try to rename `prefs.js` (prefsOLD.js) to check for issues with the preferences.

Make sure that Firefox is closed when you make changes to the profile folder.

**Comment by Naezr** [comment]
It turned out to be a coincidence. This problem is not really related to your theme. I reinstalled the browser and the bug disappeared.
