### ISSUE TITLE
Cannot pin/unpin extensions anymore.

### ISSUE THREAD

**Issue by VaiTheCatto** [Tagggar/Firefox-Alpha#6]
I tried unpinning some of my extensions from the top right but i cant right click them or even click on them

**Comment by VaiTheCatto** [comment]
one more thing. when i click on them, it just opens a new tab

**Comment by Tagggar** [comment]
> I tried unpinning some of my extensions from the top right but i cant right click them or even click on them


Hello, thank you for feedback. 
To configure extensions position:

1. You need to restart Firefox in Troubleshoot mode (without themes / extensions):
`Alt` > `Help`  > `Troubleshoot Mode` 

2. Pin / unpin / adjust extensions from customization menu and restart.

**Comment by Tagggar** [comment]
All buttons have been removed to maximize space for Tabs and to enhance the overall UI simplicity.

You can unhide Extensions button by deleting the `*/`  in the Hide Items section of  the `userChrome.css` file:

```
/* ❌ Extensions Menu */
#unified-extensions-button,

to 

/* ❌ Extensions Menu
#unified-extensions-button,

```

After, you can easily customize the position of the Extensions Menu, for example:

```
#unified-extensions-button {
  position: fixed !important;
  top: 38px;
  right: 8px;
  z-index: 2 !important;
}

```

**Comment by VaiTheCatto** [comment]
i see. i think i fixed it by unpinning all my extensions. what if i have to access a menu for ublock origin or smth. gestureify?

**Comment by Tagggar** [comment]
1. Full Extensions settings can be accessed via the shortcut: `Ctrl + Shift + A`, 
or through the browser's main menu: 
`Alt` > `Tools` > `Add-ons`

2. Some extensions are available via the context menu like uBlock:
 `RMB` > `Block Element`.
 
3. Other extensions, such as Gesturefy, do not require constant tweaking after the initial setup. Therefore, keeping them in the extensions menu is unnecessary.

 Certainly, if you utilize numerous extensions that require frequent menu access, you can display the ❌ Extensions Menu, as detailed above.

**Comment by VaiTheCatto** [comment]
Understood. Thank You.

**Comment by AeliusSaionji** [comment]
The menu doesn't necessarily need be clickable or visible, but it does need to exist in order for other extensions to draw their own popups when invoked by shortcut.

The current default should probably be changed so it doesn't break invoking extension popup by their keyboard shortcut.

**Comment by AeliusSaionji** [comment]
On this line
https://github.com/Tagggar/Firefox-Alpha/blob/78bf9a9ea57538b0a58212731e81dea80d490105/chrome/userChrome.css#L365

I replaced with this

```css
#unified-extensions-button {
  position: fixed !important;
  top: 0px;
  left: 0px;
  z-index: -1 !important;
}
```

The z-index: -1 seems to do the trick. The rest is just moving the popup menu to the top left.

I want to stress: I do not know any css, I'm just poking at this.

**Comment by Tagggar** [comment]
Hello, and thanks for the feedback.

Yes, that's actually how it works. The main goal of this configuration is to demonstrate the ease of using the browser by removing the UI clutter. Thus, everything is hidden and minimalist by default, while all functionality is preserved for 90% of users.

Moreover, the code is easily configurable to customize the UI to suit your needs.

**Comment by VaiTheCatto** [comment]
Ok thanks a lot for da help :D

**Comment by AeliusSaionji** [comment]
> Yes, that's actually how it works. The main goal of this configuration is to demonstrate the ease of using the browser by removing the UI clutter.

To be clear, the Z index of -1 keeps it hidden, so this is a purely functional change without visual impact.
When you invoke an unpinned extension by its browser shortcut, it opens the unified menu and the extension is rendered inside the unified menu.

The current css appears to actually _remove_ the unified menu as opposed to hiding it, which breaks the browser's ability to invoke unpinned extensions.

> functionality is preserved for 90% of users.

This project is, to paraphrase you and my own experience, encouraging users to keep extensions unpinned. That should be fine- we don't need to keep uBlock pinned when we can bind `Alt+o` to access the UI, for example.
![image](https://github.com/Tagggar/Firefox-Alpha/assets/4342746/5214b2f5-60ef-4d90-ac96-e6cf15e76913)

But, as mentioned above, the current css implementation denies us this option.

> the code is easily configurable to customize the UI to suit your needs.

I think you've done a great job at that- I've never really been able to successfully tweak css before. But I am suggesting that this specific scenario is a solvable bug and not a UI customization.
