### ISSUE TITLE
Misc wrong colors somehow?

### ISSUE THREAD

**Issue by AeliusSaionji** [Tagggar/Firefox-Alpha#9]
Can't see what I'm typing in the URL bar:
![image](https://github.com/Tagggar/Firefox-Alpha/assets/4342746/36a10fff-6699-41b0-8edb-dc7ef6761b91)

Can't read the statusbar:
![image](https://github.com/Tagggar/Firefox-Alpha/assets/4342746/0c5f057e-c033-43e5-bee3-b94c5b1f5c92)

I'm not sure why this is happening, maybe it's an extension or theme issue on my end?

**Comment by AeliusSaionji** [comment]
I can fix the urlbar by commenting out this line https://github.com/Tagggar/Firefox-Alpha/blob/78bf9a9ea57538b0a58212731e81dea80d490105/chrome/userChrome.css#L350

I can fix the statusbar by adding `color: white` after this line
https://github.com/Tagggar/Firefox-Alpha/blob/78bf9a9ea57538b0a58212731e81dea80d490105/chrome/userChrome.css#L127

I'm not a designer and I don't know how you want it to look, but I think this is where you'd need to start looking.

thanks!

**Comment by Tagggar** [comment]
> I'm not sure why this is happening, maybe it's an extension or theme issue on my end?

Yes, this is because the Adaptive Color extension dynamically changes the color of the fonts, and in some cases, the contrast is bad.

At this moment, you can address the URL popup color issue by replacing `Status Panel` section:

```
/* 🔗 Status Panel [Url Popup] */
#statuspanel #statuspanel-label {
  font-weight: 600 !important;
  padding-inline: var(--6) !important;
  border-radius: var(--6) !important;
  margin: var(--8) !important;
  background-color: black !important;
  color: lightgrey !important;
}
```

This code will be implemented in future releases.
